// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS. '
          'Run FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS. '
          'Run FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows. '
          'Run FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux. '
          'Run FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDLqRhy4Pjc3FuqmowWnlraRsUVEupcr7M",
      authDomain: "list1-c0834.firebaseapp.com",
      projectId: "list1-c0834",
      storageBucket: "list1-c0834.appspot.com", // ✅ Correção
      messagingSenderId: "109265050586",
      appId: "1:109265050586:web:6059960ac5c788746c3ee3",
      measurementId: "G-8KP0P9EHL7");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDLqRhy4Pjc3FuqmowWnlraRsUVEupcr7M",
    projectId: "list1-c0834",
    storageBucket: "list1-c0834.appspot.com", // ✅ Correção
    messagingSenderId: "109265050586",
    appId: "1:109265050586:web:6059960ac5c788746c3ee3",
  );
}
